src/App.tsx, src/layout/join/index.tsx, src/layout/join/style.ts, src/layout/login/index.tsx, src/layout/modal.tsx
- [CHORE:: 폴더 구조 변경](https://github.com/double-sxck/infinity-v3/commit/2352c0270c87285a5eaa038ca892da974e580344)
<br>
- 회원가입 모달을 위한 모달 폴더 분리
<br>
=> CHORE:: 폴더 구조 변경

src/assets/images/BrashIcon.tsx, src/assets/images/CoffeeIcon.tsx, src/assets/images/HeartArrowIcon.tsx, src/assets/images/Image.tsx, src/assets/images/Images.tsx, src/layout/LoginModal/join/index.tsx, src/layout/LoginModal/login/index.tsx
=> FIX:: icon rem으로 변환

src/components/userPage/index.tsx
- API 수정에 따라 코드 변경
<br>
- 제곧내
<br>
=> ADD:: 유저 정보 수정된 API로 변경

src/components/main/index.tsx, src/components/view/index.tsx, src/layout/CommentModal/index.tsx
=> FIX:: modal

src/components/header/index.tsx, src/components/sidebar/icons/GenreIconComponents.tsx, src/components/sidebar/index.tsx, src/components/sidebar/style.ts
- [ADD:: routing](https://github.com/double-sxck/infinity-v3/pull/32/commits/160202527e35fb16a967eae7bfa53bf387f4c8ae)
<br>
- 라우팅 추가
<br>
=> ADD:: routing

src/components/write/style.ts, src/layout/CommentModal/style.ts
=> DESIGN:: 줄글 가독성 증가

src/components/write/style.ts, src/layout/CommentModal/style.ts, src/layout/LoginModal/join/style.ts, src/layout/LoginModal/login/index.tsx, src/layout/LoginModal/login/style.ts
=> DESIGN:: 커서 스타일 지정

src/components/write/index.tsx
=> CHORE:: 키워드 추가 시 자동으로 아래로 스크롤되게 변경

src/components/write/index.tsx, src/components/write/style.ts
=> FIX:: 소설 생성 중 api 못 보내게 변경

src/components/view/style.ts
=> CHORE:: 글 올리기 버튼 커서 포인터로 변경

src/components/write/index.tsx, src/components/write/style.ts
=> CHORE:: 키워드 추가 UX 향상

src/components/sidebar/index.tsx, src/components/view/index.tsx
=> CHORE:: 로컬스토리지 관리

src/components/header/index.tsx
=> CHORE:: 검색어 입력 없을 시 검색되지 않게 변경

package.json, src/App.tsx, src/components/view/index.tsx, src/components/view/style.ts, src/components/write/index.tsx, src/components/write/style.ts, src/layout/LoginModal/join/index.tsx, src/layout/LoginModal/join/style.ts, src/layout/LoginModal/login/index.tsx, src/layout/LoginModal/login/style.ts, src/toasts/customToast.tsx, src/toasts/customToastContainer.tsx, yarn.lock
- 토스트 추가
<br>
- 토스트 알림으로 에러, 완료 메시지 표시
<br>
=> ADD:: 토스트 알림을 통한 에러 핸들링

src/components/main/index.tsx
=> CHORE:: 주석 제거

src/components/main/index.tsx
- [ADD: 무한 스크롤 구현 test X](https://github.com/double-sxck/infinity-v3/commit/a8f3c311ae9c786b0ff78a90fb6ccb032c59a5aa)
<br>
- 무한 스크롤 구현 테스트 완료
<br>
=> ADD: 무한 스크롤 구현 test X

src/components/write/index.tsx, src/components/write/style.ts
=> ADD:: 생성한 소설 롤백 기능 추가

src/components/view/index.tsx, src/components/view/modal.tsx, src/components/view/style.ts
=> ADD:: 썸네일 생성 페이지에서 키워드와 소설 확인 기능 추가

src/components/write/index.tsx
=> ADD:: 썸네일 화면에서 뒤로가기 했을 때 키워드와 소설 데이터 유지돼있게 변경

src/components/main/index.tsx, src/components/search/index.tsx
=> FIX:: 무한 스크롤과 정렬 기능 제대로 동작하도록 수정

src/components/main/index.tsx
=> CHORE:: 콘솔 출력문 삭제

src/components/main/index.tsx, src/components/main/loading.tsx, src/components/main/style.ts
=> ADD:: 로딩 중 요소 디자인

src/components/header/index.tsx
=> FIX:: 검색창 특수문자 처리

src/components/userPage/index.tsx, src/components/userPage/style.ts
=> FIX:: 새로고침시 내 정보의 소설이 불러와지지 않는 문제 수정

src/components/main/index.tsx
=> CHORE:: 무한스크롤 observer 위치 변경

src/components/write/index.tsx
=> CHORE:: 키워드 추가에 유저 아이콘 크기 조정

src/layout/CommentModal/index.tsx, src/layout/CommentModal/style.ts
=> ADD:: 내 소설 삭제 기능 추가 & DESIGN:: 소설 모달 로딩 중 디자인 추가

src/components/write/index.tsx
=> CHORE:: 키워드, 소설 데이터 바로 로컬스토리지에 저장

src/layout/CommentModal/index.tsx
=> MODIFY:: 소설 모달 변경된 api에 맞게 수정

src/components/main/index.tsx
=> FIX:: 메인페이지 렌더링 이슈 해결

src/layout/LoginModal/join/index.tsx, src/layout/LoginModal/login/index.tsx
=> ADD:: 로그인, 회원가입 입력창 자동 포커스

yarn.lock
- [FIX: npm package remove](https://github.com/double-sxck/infinity-v3/commit/55c39253d2a00eaeede986968a053cc36f0eb2be)
<br>
- npm package Remove
<br>
=> FIX: npm package remove

src/components/write/index.tsx
- [FIX: 한글 두번 입력 오류 수정](https://github.com/double-sxck/infinity-v3/commit/ceb8db88f816e4eee4c48126cbb2a74ab6ff838e)
<br>
- 한글 onKeyDown시 두번 입력 오류 해결(onKeyUp사용)
<br>
=> FIX: 한글 두번 입력 오류 수정

src/components/view/index.tsx, src/components/view/style.ts, src/components/write/index.tsx, src/components/write/style.ts
- [x ]코드 스타일 변경(Code style update) (formatting, local variables)
- [ADD: 소설 직접 수정 기능 추가](https://github.com/double-sxck/infinity-v3/commit/bea9c2e52ad0355d4431177521215b95af5d55dd)
<br>
- 소설 직접 수정 기능 추가
- image url 확인 간편화
<br>
=> ADD: 소설 직접 수정 기능 추가

src/layout/CommentModal/index.tsx
=> FIX:: 없어진 api 불러오는 코드 제거

src/components/write/index.tsx, src/components/write/style.ts
=> FIX:: textarea로 자동스크롤 이전, 소설 생성 중에 변경 막음

src/layout/CommentModal/index.tsx
- [FIX: 한글 댓글 2번 입력 오류 수정](https://github.com/double-sxck/infinity-v3/commit/2ff77e8f50e5c3f68030c90e93674f1532de4932)
<br>
- 한글 2번 입력 오류 수정
#89 
<br>
=> FIX: 한글 댓글 2번 입력 오류 수정

src/components/userPage/page/user.tsx
- [ADD: 구현 안된 기능 예외 처리](https://github.com/double-sxck/infinity-v3/commit/3aa7e9e90ff4f9c22b0be878b9eda0d6eb003d5f)
<br>
- 구현 되지 않은 기능 예외 처리
#95 
<br>
=> ADD: 구현 안된 기능 예외 처리

src/components/main/index.tsx
- [FIX: 무한 스크롤 오류](https://github.com/double-sxck/infinity-v3/commit/e58438a0de2aa1d1a2eed0140a9938959d3e5806)
<br>
- 무한 스크롤 오류해결(더 이상 데이터가 없으면 get 하지 않음)
#97 
<br>
=> FIX: 무한 스크롤 오류
